# 자료규조

1. 리스트 (기본구조) [1,2]

2. 튜플(상수, 불변) (1,2)

3. 딕셔너러(key: value) <<- json{1:'양진욱', 2:'백혜림', 3:'박윤수'}

4. 세트(set): 집합 set()

5. 배열(numpy)

6. 판다스 구조(series, DataFrame)



## 넘파이

- 배열(array) 생성, 연산

- 배열(array): 하나의 데이터 타입 허용, 다차원 자료구조

### 생성과 색인

In [1]:
#1. 넘파이 생성
import numpy as np
np.array([1,2,3])
# array([1, 2, 3]) 1차원 배열

np.array([[1,2,3],[4,5,6],[7,8,9]])
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])
# 2차원 배열(수리적 모형:행열)
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# array([[[ 1,  2,  3],
#         [ 4,  5,  6]],

#        [[ 7,  8,  9],
#         [10, 11, 12]]])
#3차원 배열

np.arange(1,26) #1차원
# array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
#       18, 19, 20, 21, 22, 23, 24, 25]) 인자가 25개
np.arange(1,26).reshape(5,5) #2차원
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25]])
np.arange(1,26).reshape(5,-1) #2차원
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25]])
a1=np.arange(1,26)
type(a1)

numpy.ndarray

In [2]:
#2. 색인 
a2= np.array([[1,2,3],[4,5,6,],[7,8,9]])
a2[1,:]
# array([4, 5, 6])

# 정수 색인(두번째 열 선택: 차원 축소 발생)
a2[:,1]
# array([2, 5, 8])

#슬라이스 색인 (두번째 열 선택: 차원 축소 발생안함)
a2[:,1:2]
# array([[2],
#        [5],
#        [8]])

#a2에서 1,3행 선택
a2[0:3:2,:]   #0부터 시작 3전까지 2칸 단위로
# array([[1, 2, 3],
#        [7, 8, 9]])
a2[[0,2],:]
# array([[1, 2, 3],
#        [7, 8, 9]])

#a2에서 1,3열 선택
a2[:,[0,2]]
# array([[1, 3],
#        [4, 6],
#        [7, 9]])

a2
a2[1,1] #5

a2[[1,2],[1,2]] #array([5, 9])
#>>>a2[1,1],a2[2,2] 포인트 인덱싱
#2개의 포인트(점)출력
#색인함수(ix_()) 사용하여 해결

a2[np.ix_([1,2],[1,2])]
# array([[5, 6],
       # [8, 9]])
a2[[0,2],[0,2]] #array([1, 9])

#np.ix_?

#조건 색인
a2
a2 > 5
# array([[False, False, False],
#        [False, False,  True],
#        [ True,  True,  True]])

a2[a2>5]
#array([6, 7, 8, 9]) true만 출력

a2[:,0]>5 
#첫번째 컬럼 가져와서 5이상 행만 선택

a2[a2[:,0]>5]
#array([[7, 8, 9]])
#조건의 결과를 행방향에 색인 값으로 전달

array([[7, 8, 9]])

### 함수 등의 적용

메서드, 연산, 형(데이터 타입) 변환, np.where 함수, 산술 연산, 전치 메서드

In [3]:
# 3. 메서드
dir(a2) #쓸수있는 것을 보여줌

a2.dtype    # numpy 구성 데이터 타입
a2.shape    # mumpy 모양(shape)
# (3, 3)
a2.shape[0] # mumpy행의수
a2.shape[1] # mumpy열의 수

a2.reshape(1,9) #array 모양 변경
# array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
a2.ndim   #array 차원

In [ ]:
# 4. 연산
[1,2,3]+[4,5,6]  #list는 서로 원소끼리 연산불가 (확장으로 해석)
# [1, 2, 3, 4, 5, 6]

np.array([1,2,3])+np.array([4,5,6])
# array([5, 7, 9])
np.array([1,2,3])+np.array([4,5,6,7])
#사이즈가 같아야됨

In [ ]:
# 5.형(데이터 타입) 변환 메드서

a2.astype('float')
# array([[1., 2., 3.],
#        [4., 5., 6.],
#        [7., 8., 9.]])
a2.astype('int')
a2.astype('str')
# array([['1', '2', '3'],
#        ['4', '5', '6'],
#        ['7', '8', '9']], dtype='<U11')

In [ ]:
# 6. np.where 함수
# if문의 축약
#np.where(조건, 참인 값 변환, 거짓인 값 변환)
# spl 문 기본형 select * fromm db where

np.where(a2>5,'A','B')

In [ ]:
# 7.산술 연산 메서드
a2
a2.sum()
a2.mean()
a2.var()
a2.std()
a2.min()
a2.max()

(a2 > 5).sum() #a2에서 5보다 튼 값의 수
(a2 > 5).any() #true a2에서 5보다 큰 값이 하나라도 있을 경우
(a2 > 5).all() #true a2에서 모두 5보다 클 경우만 참

a2
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])
a2.sum(axis=0) #행끼리 더해줘/행 기준 행 별 총함(서로 다른 행끼리, 세로방향 연산)
 # array([12, 15, 18])
a2.sum(axis=1) #열끼리 더해줘
# array([ 6, 15, 24])

#[축 번호]
#2차원: 행(0),열(1)
#3차원: 층(0),행(1), 열(2)

In [ ]:
#8.전치 메서드
#1)T:행과 열을 전치
np.arange(1,9)
# array([1, 2, 3, 4, 5, 6, 7, 8])
a1=np.arange(1,9).reshape(4,2)
a1
# array([[1, 2],
#        [3, 4],
#        [5, 6],
#        [7, 8]])
a1.T
# array([[1, 3, 5, 7],
#        [2, 4, 6, 8]])

#2) swapaxes: 2축을 전달받아 두축을 서로 전치, 전달 순서는 중요하지 않음
a1.swapaxes(0,1)
a1.swapaxes(1,0)
# array([[1, 3, 5, 7],
#        [2, 4, 6, 8]])

#3) transpose
#원본의 차원에 맞는 축번호를 인수에 차례대로 전달. 그리고 전치 전달되는 순서 중요
a1.transpose(0,1) #원본그대로 
# array([[1, 2],
#        [3, 4],
#        [5, 6],
#        [7, 8]])
a1.transpose(1,0) #행렬 전치 
# array([[1, 3, 5, 7],
#        [2, 4, 6, 8]])

### 넘파이 외부파일 입출력

In [ ]:
# 9. 외부 파일 입출력
# 1)파일 불러오기
# np.loadtxt(파일명,
#            데이터타입,
#            필드 구분 기호,
#            skip 할 행의 수,
#            선택할 컬럼의 값(위치),
#            인코딩 옵션)
import numpy as np
np.loadtxt('C:/Users/nadai/code/data_bigdata_cert/file1.txt', delimiter=',', dtype='str')
np.loadtxt('./code/data_bigdata_cert/file1.txt', delimiter=',', dtype='str')

# 2)파일 내려쓰기
# np.savetxt(fname,       파일명
#            x,           객체명
#            delimiter,  구분자
#            fmt,        출력형식(format)
#            header,     해더 출력 여부(파일 첫 문자열)
#            encoding)    인코딩 옵션

x=np.arange(0.0,5.0,1.0)
np.savetxt('file2.txt', x, delimiter=',', fmt='%s')
#'%s': 문자 타입

# #[참고]: fmt 전달/변경 방식
# %s: 문자열
# %f: 실수(float)
# %d: 정수
'%s' %123   #'123'
'%f' %123   #'123.000000'
'%.4f' %123 #'123.0000' 소수점 4째 자리까지
'%d' %123   #'123'
'%7d' %123  #'    123'